### ISSUE TITLE
Sample does not work with dotnet 3.1 + ASP.NET Core 3.1

### ISSUE THREAD

**Issue by alexmarshall132** [mjisaak/angular-aadb2c#2]
This sample no longer appears to work under ASP.NET Core 3.1. Migration of dotnet 2.2 and ASP.NET Core 2.2 applications to 3.1 is now required since Microsoft has End-Of-Lifed dotnet 2.2 and 3.0 in favour of 3.1 and 2.1 for LTS. Can I ask that you update this to 3.1 ? It's very promising but I keep running into a bug that seems to be an issue with the Azure AD B2C package, and I'd like to confirm whether I've made a mistake or not.

**Comment by mjisaak** [comment]
@alexmarshall132 I will try to migrate the API to .NET 3.1 and give you feedback.

**Comment by mjisaak** [comment]
I migrated the project to .NET Core 3.1 and Angular 9. I had some issues with the Startup configuration, maybe that was your issue? 
#3

**Comment by alexmarshall132** [comment]
@mjisaak Just saw the notification for this. Will try it out and report back. Thank you so much!

**Comment by mjisaak** [comment]
> @mjisaak Just saw the notification for this. Will try it out and report back. Thank you so much!

You are welcome @alexmarshall132 . If you still have any issues just tell me.

**Comment by alexmarshall132** [comment]
I'm still unable to get this working, but I don't think it's anything to do with the tutorial. I had made changes that match what was committed earlier in this thread. I'm running into the issue of getting an exception when the Service authorizes the token presented by the client:

IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/<my b2c domain>.onmicrosoft.com/B2C_1_<my signup flow name>/v2.0/.well-known/openid-configuration'.

The format of the configuration url does not match the format of the URL for the Discovery Document field in the client. Having dug into the Microsoft.AspNetCore.Authentication.AzureADB2C.UI nuget package, it appears that the AzureADB2COpenIdConnectOptionsConfiguration.BuildAuthority method generates an incorrectly formatted URL, which is nothing to do with this tutorial. I must be missing something if you're able to get this to work with dotnet 3.1, I just don't know what. Thank you for your help in upgrading the sample, it's much appreciated.

**Comment by mjisaak** [comment]
@alexmarshall132 afraid to hear that :-/.
I just tried it again on another PC and it worked. This is what I did:

* Clone the repository
* Start the API project
  * Change working directory to ./foo.api
  * Start it using `dotnet run`
* Start the Web App
  * Change working directory to ./foo.web
  * Install packages using `npm install`
  * Start it using `ng serve`

Here is a [screenshot](https://imgur.com/a/W0PJZjT) from the demo and a [screenshot from the runtime versions](https://imgur.com/a/3gOzWl4) I am using.

Maybe a firewall / proxy issue?

**Comment by alexmarshall132** [comment]
Issue solved: legacy configuration value was missed. Thank you so much for your help @mjisaak , it's much appreciated.
