### ISSUE TITLE
login url

### ISSUE THREAD

**Issue by ac3ju** [mjisaak/angular-aadb2c#4]
Hi thx you very much for this sample, it helps a lot !

For the login url in conf,   loginUrl: 'https://aboutazure.b2clogin.com/aboutazure.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_susi',

Why is this the same of the token ? and not "/authorize" ?

**Comment by mjisaak** [comment]
Hi @ac3ju. Thanks for your feedback.

These are the values from the discovery document:
![image](https://user-images.githubusercontent.com/8446917/81060223-50e9d700-8ed2-11ea-8900-b29c07ae1e8a.png)

Can't tell you why they are the same, however, it works ;-)
